spring:
  servlet:
    encoding:
      charset: UTF-8
  http:
    encoding:
      mandatory-file-encoding: UTF-8
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  thymeleaf:
    encoding: UTF-8
    prefix : classpath:templates/
    suffix : .html
    cache : false
    mode: HTML5
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: OJT
    password: roqkfeo#01
  h2:
    console:
      enable: true

  mvc:
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
