
spring:
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: OJT
    password: roqkfeo#01
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    static-path-pattern: /static/**
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false